# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mae-FatMan
email: lzjdsuyonghong@aliyiun.com
description: 记录开发学习过程中遇到的问题、心得和感受等等
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mae-fatman.github.io" # the base hostname & protocol for your site

github_username:  Mae-FatMan
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

paginate: 10
paginate_path: "page:num"

# highlight
highlighter: pygments
#highlighter: rouge

theme: jekyll-theme-cayman